Areas/Admin/ViewModels/ItemMenuViewModel.cs
using System.ComponentModel.DataAnnotations;
using Yummy.Models;

namespace Yummy.Areas.Admin.ViewModels
{
    public class ItemMenuViewModel:BaseModelVM
    {
        [Display(Name = "Name")]
        [Required]
        public string ItemMenuName { get; set; }
        [Display(Name = "Breef")]
        [Required]
        public string ItemMenuBreef { get; set; }
        [Display(Name = "Price")]
        [Required]
        public double ItemMenuPrice { get; set; }
        [Display(Name = "Image")]
        [Required]
        public string ItemMenuImage { get; set; }
        [Display(Name = "File")]
        public IFormFile? File { get; set; }
        [Display(Name = "Category")]
        [Required]
        public int CategoryMenuId { get; set; }
        public CategoryMenu? CategoryMenu { get; set; }
    }
}

Models/ItemMenu.cs
using System.ComponentModel.DataAnnotations;

namespace Yummy.Models
{
    public class ItemMenu:BaseEntity
    {
        public int ItemMenuId { get; set; }
        [Display(Name = "Name")]
        public string ItemMenuName { get; set;}
        [Display(Name = "Breef")]
        public string ItemMenuBreef { get; set;}
        [Display(Name = "Price")]
        public double ItemMenuPrice { get; set; }
        [Display(Name = "Image")]
        public string ItemMenuImage { get; set; }
        [Display(Name ="Category")]
        public int CategoryMenuId { get; set; }
        public CategoryMenu? CategoryMenu { get; set; }
    }
}

Areas/Admin/Controllers/ItemMenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Claims;
using Yummy.Areas.Admin.ViewModels;
using Yummy.Models;
using Yummy.Models.Repositories;

namespace Yummy.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ItemMenuController : Controller
    {
        public IRepository<ItemMenu> _ItemMenu { get; }
        public IWebHostEnvironment Host { get; }
        public IRepository<CategoryMenu> _CategoryMenu { get; }

        public ItemMenuController(IRepository<ItemMenu> itemMenu,IWebHostEnvironment host,IRepository<CategoryMenu> categoryMenu)
        {
            _ItemMenu = itemMenu;
            Host = host;
            _CategoryMenu = categoryMenu;
        }
        // GET: ItemMenuController
        public ActionResult Index()
        {
            return View(_ItemMenu.View());
        }


        // GET: ItemMenuController/Create
        public ActionResult Create()
        {
            ViewBag.CategoryMenuList = _CategoryMenu.View();
            return View();
        }

        // POST: ItemMenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemMenuViewModel collection)
        {
            try
            {
                if(collection.File == null) {
                    ModelState.AddModelError("", "The file field is required");
                    return View();
                }
                var obj = new ItemMenu
                {
                    ItemMenuBreef = collection.ItemMenuBreef,
                    ItemMenuName = collection.ItemMenuName,
                    ItemMenuPrice = collection.ItemMenuPrice,
                    ItemMenuImage = UploadImage(collection.File),
                    IsActive = true,
                    CreateDate = DateTime.Now,
                    CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    CategoryMenuId = collection.CategoryMenuId,
                };
                _ItemMenu.Add(obj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemMenuController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.CategoryMenuList = _CategoryMenu.View();
            var data = _ItemMenu.Find(id);
            var obj = new ItemMenuViewModel
            {
                ItemMenuBreef = data.ItemMenuBreef,
                ItemMenuName=data.ItemMenuName,
                ItemMenuPrice = data.ItemMenuPrice,
                CategoryMenuId = data.CategoryMenuId
            };
            return View(obj);
        }

        // POST: ItemMenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ItemMenuViewModel collection)
        {
            try
            {
                var data = _ItemMenu.Find(id);
                data.ItemMenuName = collection.ItemMenuName;
                data.ItemMenuPrice = collection.ItemMenuPrice;
                data.ItemMenuBreef = collection.ItemMenuBreef;
                data.ItemMenuImage = (collection.File != null)? UploadImage(collection.File):data.ItemMenuImage;
                data.EditDate = DateTime.Now;
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                data.CategoryMenuId = collection.CategoryMenuId;
                _ItemMenu.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemMenuController/Delete/5
        public ActionResult Delete(int idDelete)
        {
            var data = _ItemMenu.Find(idDelete);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _ItemMenu.Delete(idDelete, data);
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Active(int idActive)
        {
            var data = _ItemMenu.Find(idActive);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _ItemMenu.Active(idActive, data);
            return RedirectToAction(nameof(Index));
        }

        public string UploadImage(IFormFile file)
        {
            string image = "";
            if(file != null)
            {
                string path = Path.Combine(Host.WebRootPath,"ItemMenuImg");
                Directory.CreateDirectory(path);
                FileInfo fileInfo = new FileInfo(file.FileName);
                image = Guid.NewGuid() + fileInfo.Extension;
                string FullPath = Path.Combine(path, image);
                file.CopyTo(new FileStream(FullPath, FileMode.Create));
            }
            return image;
        }
    }
}

Areas/Admin/Views/ItemMenu/Create.cshtml
@model Yummy.Areas.Admin.ViewModels.ItemMenuViewModel

@{
    ViewData["Title"] = "Create";
}


<div class="full_container">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

                <div class="logo_login">
                    <div class="center">
                        <img width="210" src="~/images/logo/logo.png" alt="#" />
                    </div>
                </div>

                <div class="login_form">

                    <form asp-action="Create" enctype="multipart/form-data" class="row g-3">
                        <fieldset>
                            <div class="field">
                                <label asp-for="ItemMenuBreef" class="control-label"></label>
                                <input asp-for="ItemMenuBreef" class="form-control" />
                                <span asp-validation-for="ItemMenuBreef" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="ItemMenuName" class="control-label"></label>
                                <input asp-for="ItemMenuName" class="form-control" />
                                <span asp-validation-for="ItemMenuName" class="text-danger"></span>
                            </div>
                           
                            <div class="field">
                                <label asp-for="File" class="control-label"></label>
                                <input asp-for="File" class="form-control" />
                                <span asp-validation-for="File" class="text-danger"></span>
                            </div>
                            <div asp-validation-summary="ModelOnly" class="text-danger "></div>

                            <div class="field">
                                <label asp-for="ItemMenuPrice" class="control-label"></label>
                                <input asp-for="ItemMenuPrice" class="form-control" />
                                <span asp-validation-for="ItemMenuPrice" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="CategoryMenuId" class="control-label"></label>
                                <select asp-for="CategoryMenuId" class="form-control form-select" asp-items="@(new SelectList(ViewBag.CategoryMenuList,"CategoryMenuId","CategoryMenuName"))"></select>
                                <span asp-validation-for="CategoryMenuId" class="text-danger"></span>
                            </div>

                            <div class="text-center mb-2 mt-2">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                            <div class="text-center">
                                <a asp-action="Index" class="btn btn-success">Back to Table</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/ItemMenu/Edit.cshtml
@model Yummy.Areas.Admin.ViewModels.ItemMenuViewModel

@{
    ViewData["Title"] = "Edit";
}


<div class="full_container">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

                <div class="logo_login">
                    <div class="center">
                        <img width="210" src="~/images/logo/logo.png" alt="#" />
                    </div>
                </div>

                <div class="login_form">

                    <form asp-action="Edit" enctype="multipart/form-data" class="row g-3">
                        <fieldset>
                            <div class="field">
                                <label asp-for="ItemMenuBreef" class="control-label"></label>
                                <input asp-for="ItemMenuBreef" class="form-control" />
                                <span asp-validation-for="ItemMenuBreef" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="ItemMenuName" class="control-label"></label>
                                <input asp-for="ItemMenuName" class="form-control" />
                                <span asp-validation-for="ItemMenuName" class="text-danger"></span>
                            </div>
                            
                            <div class="field">
                                <label asp-for="File" class="control-label"></label>
                                <input asp-for="File" class="form-control" />
                                <span asp-validation-for="File" class="text-danger"></span>
                            </div>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="field">
                                <label asp-for="ItemMenuPrice" class="control-label"></label>
                                <input asp-for="ItemMenuPrice" class="form-control" />
                                <span asp-validation-for="ItemMenuPrice" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="CategoryMenuId" class="control-label"></label>
                                <select asp-for="CategoryMenuId" class="form-control form-select"  asp-items="@(new SelectList(ViewBag.CategoryMenuList,"CategoryMenuId","CategoryMenuName"))"></select>
                                
                                <span asp-validation-for="CategoryMenuId" class="text-danger"></span>
                            </div>

                            <div class="text-center mb-2 ">
                                <input type="submit" value="Edit" class="btn btn-primary" />
                            </div>
                            <div class="text-center">
                                <a asp-action="Index" class="btn btn-success">Back to Table</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/ItemMenu/Index.cshtml
@model IEnumerable<Yummy.Models.ItemMenu>

@{
    ViewData["Title"] = "Index";
}

<div class="full_container">
    <div class="container">
        <div class="full_height">
          <div class="col-md-12 mb-3">
            <div class="white_shd full margin_bottom_30">
        <div class="full graph_head">
            <div class="heading1 margin_0">
        <h2>
            
                <a asp-action="Create">Create New</a>
            
        </h2>
            </div>
        </div>
 <div class="table_section padding_infor_info">
     <div class="table-responsive-sm">
       <table class="table table-dark table-striped"> 
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemMenuName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemMenuBreef)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemMenuPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemMenuImage)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.CategoryMenu.CategoryMenuName)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemMenuName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemMenuBreef)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemMenuPrice)
            </td>
            <td>
                <img src="~/ItemMenuImg/@item.ItemMenuImage" style="width:90px;height:90px"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryMenu.CategoryMenuName)
            </td>
           
            <td> 
                <a asp-action="Edit" asp-route-id="@item.ItemMenuId"><i class="fa fa-edit"> </i></a> |
                    <a href="" class="butDelehhh" data-toggle="modal" data-target="#myModal" data-bfc=@Url.ActionLink("Delete","ItemMenu",new{idDelete = item.ItemMenuId})><i class="fa fa-close"></i></a> |
                    @if (item.IsActive)
                    {
                        <a asp-action="Active" asp-route-idActive="@item.ItemMenuId"><i class="fa fa-eye"></i></a>
                    }
                    else
                    {
                        <a asp-action="Active" asp-route-idActive="@item.ItemMenuId"><i class="fa fa-eye-slash"></i></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>




<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
                Are you sure?
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button id="confirmDelt" type="button" class="btn btn-danger" data-dismiss="modal">Delete</button>
                <button id="cancelDelt" type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/jquery/jquery.js"></script>



<script>
    var dataDeleteInfo = "";
    $(".butDelehhh").click(function () {
        dataDeleteInfo = $(this).data("bfc")
    })

    $("#confirmDelt").click(function () {
        window.location = dataDeleteInfo;
        dataDeleteInfo = ""
    })

    $("#cancelDelt").click(function () {
        dataDeleteInfo = ""
    })

</script>