Areas/Admin/ViewModels/AboutUsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Yummy.Areas.Admin.ViewModels
{
    public class AboutUsViewModel:BaseModelVM
    {
        [Display(Name = "Image 1")]
        public string AboutUsImage1 { get; set; }
        [Display(Name = "Image 2")]
        public string AboutUsImage2 { get; set; }
        [Display(Name = "Paragraph 1 ")]
        public string AboutUsParagraph1 { get; set; }
        [Display(Name = "Paragraph 2 ")]
        public string AboutUsParagraph2 { get; set; }
        [Display(Name = "Point 1 ")]
        public string AboutUsPoint1 { get; set; }
        [Display(Name = "Point 2 ")]
        public string AboutUsPoint2 { get; set; }
        [Display(Name = "Point 3 ")]
        public string AboutUsPoint3 { get; set; }
        [Display(Name = "Link")]
        public string AboutUsLink { get; set; }
        [Display(Name = "Title")]
        public string AboutUsTitle { get; set; }
        [Display(Name = "Phone Note")]
        public string AboutUsPhoneNote { get; set; }
        [Display(Name ="File 1")]
        public IFormFile? File1 { get; set; }
        [Display(Name = "File 2")]
       
        public IFormFile? File2 { get; set; }

    }
}

Models/AboutUs.cs
using System.ComponentModel.DataAnnotations;

namespace Yummy.Models
{
    public class AboutUs:BaseEntity
    {
        public int AboutUsId { get; set; }
        [Display(Name ="Image 1")]
        public string AboutUsImage1 { get; set; }
        [Display(Name = "Image 2")]
        public string AboutUsImage2 { get; set; }
        [Display(Name = "Paragraph 1 ")]
        public string AboutUsParagraph1 { get; set; }
        [Display(Name = "Paragraph 2 ")]
        public string AboutUsParagraph2 { get; set; }
        [Display(Name = "Point 1 ")]
        public string AboutUsPoint1 { get; set; }
        [Display(Name = "Point 2 ")]
        public string AboutUsPoint2 { get; set; }
        [Display(Name = "Point 3 ")]
        public string AboutUsPoint3 { get; set; }
        [Display(Name = "Link")]
        public string AboutUsLink { get; set; }
        [Display(Name = "Title")]
        public string AboutUsTitle { get; set; }
        [Display(Name = "Phone Note")]
        public string AboutUsPhoneNote { get; set; }
    }
}

Areas/Admin/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Yummy.Areas.Admin.ViewModels;
using Yummy.Models;
using Yummy.Models.Repositories;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Yummy.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AboutUsController : Controller
    {
        public IRepository<AboutUs> _AboutUs { get; }
        public IHostingEnvironment Host { get; }

        public AboutUsController(IRepository<AboutUs> aboutUs,IHostingEnvironment host)
        {
            _AboutUs = aboutUs;
            Host = host;
        }
        // GET: AboutUsController
        public ActionResult Index()
        {
            return View(_AboutUs.View());
        }

        

        // GET: AboutUsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AboutUsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AboutUsViewModel collection)
        {
            try
            {
                

                if (collection.File1 == null)
                {
                    ModelState.AddModelError("", "The file field required");
                    return View();

                }
                if (collection.File2 == null)
                {
                    ModelState.AddModelError("", "The file field required");
                    return View();

                }
                var obj = new AboutUs
                    {
                        AboutUsParagraph1 = collection.AboutUsParagraph1,
                        AboutUsParagraph2 = collection.AboutUsParagraph2,
                        AboutUsPoint1 = collection.AboutUsPoint1,
                        AboutUsPoint2 = collection.AboutUsPoint2,
                        AboutUsPoint3 = collection.AboutUsPoint3,
                        AboutUsLink = collection.AboutUsLink,
                        AboutUsPhoneNote = collection.AboutUsPhoneNote,
                        AboutUsTitle = collection.AboutUsTitle,
                        AboutUsImage1 = UploadImage(collection.File1),
                        AboutUsImage2 = UploadImage(collection.File2),
                        CreateDate = DateTime.Now,
                        CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                        IsActive = true,
                    };
                    _AboutUs.Add(obj);
                    return RedirectToAction(nameof(Index));
                //}
                //ModelState.AddModelError("", "Full out all Information");
                //return View();                
            }
            catch
            {
                return View();
            }
        }

        // GET: AboutUsController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = _AboutUs.Find(id);
            var obj = new AboutUsViewModel
            {
                AboutUsParagraph1 = data.AboutUsParagraph1,
                AboutUsParagraph2 = data.AboutUsParagraph2,
                AboutUsPoint1 = data.AboutUsPoint1,
                AboutUsPoint2 = data.AboutUsPoint2,
                AboutUsPoint3 = data.AboutUsPoint3,
                AboutUsLink = data.AboutUsLink,
                AboutUsTitle= data.AboutUsTitle,
                AboutUsPhoneNote= data.AboutUsPhoneNote,
            };
            return View(obj);
        }

        // POST: AboutUsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AboutUsViewModel collection)
        {
            try
            {
                //if (ModelState.IsValid)
                //{
                    var data = _AboutUs.Find(id);
                    data.AboutUsLink = collection.AboutUsLink;
                    data.AboutUsTitle = collection.AboutUsTitle;
                    data.AboutUsParagraph1 = collection.AboutUsParagraph1;
                    data.AboutUsParagraph2 = collection.AboutUsParagraph2;
                    data.AboutUsPoint1 = collection.AboutUsPoint1;
                    data.AboutUsPoint2 = collection.AboutUsPoint2;
                    data.AboutUsPoint3 = collection.AboutUsPoint3;
                    data.AboutUsPhoneNote = collection.AboutUsPhoneNote;
                    data.AboutUsImage1 = (collection.File1 != null)?UploadImage(collection.File1):data.AboutUsImage1;
                    data.AboutUsImage2 = (collection.File2 != null) ? UploadImage(collection.File2) : data.AboutUsImage2;
                    data.EditDate = DateTime.Now;
                    data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _AboutUs.Update(id,data);
                    return RedirectToAction(nameof(Index));
                //}
                //ModelState.AddModelError("","Full out all information");
                //return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: AboutUsController/Delete/5
        public IActionResult Delete(int idDelete)
        {
            var data = _AboutUs.Find(idDelete);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _AboutUs.Delete(idDelete,data);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Active(int idActive)
        {
            var data = _AboutUs.Find(idActive);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier) ;
            _AboutUs.Active(idActive,data);
            return RedirectToAction(nameof(Index));
        }


        public string UploadImage(IFormFile file)
        {
            string image = "";

            if (file != null)
            {
                string path = Path.Combine(Host.WebRootPath,"AboutUsImg");
                FileInfo info = new FileInfo(file.FileName);
                image = Guid.NewGuid() + info.Extension;
                string FullPath = Path.Combine(path, image);
                file.CopyTo(new FileStream(FullPath,FileMode.Create));
            }

            return image;
        }
    }
}

Areas/Admin/Views/AboutUs/Create.cshtml
@model Yummy.Areas.Admin.ViewModels.AboutUsViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="full_container " style="margin-top:130px;margin-bottom:130px" >
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

@* <div class="logo_login">
    <div class="center">
        <img width="210" src="~/images/logo/logo.png" alt="#" />
    </div>
</div> *@

<div class="login_form">

    <form asp-action="Create" enctype="multipart/form-data" class="row g-3">
        <fieldset>
        
            <div class="field">
                <label asp-for="File1" class="control-label"></label>
                <input asp-for="File1" class="form-control" />
                <span asp-validation-for="File1" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="field">
                <label asp-for="File2" class="control-label"></label>
                <input asp-for="File2" class="form-control" />
                <span asp-validation-for="File2" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="field">
                <label asp-for="AboutUsParagraph1" class="control-label"></label>
                <input asp-for="AboutUsParagraph1" class="form-control" />
                <span asp-validation-for="AboutUsParagraph1" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsParagraph2" class="control-label"></label>
                <input asp-for="AboutUsParagraph2" class="form-control" />
                <span asp-validation-for="AboutUsParagraph2" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPoint1" class="control-label"></label>
                <input asp-for="AboutUsPoint1" class="form-control" />
                <span asp-validation-for="AboutUsPoint1" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPoint2" class="control-label"></label>
                <input asp-for="AboutUsPoint2" class="form-control" />
                <span asp-validation-for="AboutUsPoint2" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPoint3" class="control-label"></label>
                <input asp-for="AboutUsPoint3" class="form-control" />
                <span asp-validation-for="AboutUsPoint3" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsLink" class="control-label"></label>
                <input asp-for="AboutUsLink" class="form-control" />
                <span asp-validation-for="AboutUsLink" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsTitle" class="control-label"></label>
                <input asp-for="AboutUsTitle" class="form-control" />
                <span asp-validation-for="AboutUsTitle" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPhoneNote" class="control-label"></label>
                <input asp-for="AboutUsPhoneNote" class="form-control" />
                <span asp-validation-for="AboutUsPhoneNote" class="text-danger"></span>
            </div>
          
            <div class="text-center mb-2 ">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

            <div class="text-center">
                <a asp-action="Index" class="btn btn-success">Back to Table</a>
            </div>

            </fieldset>
        </form>
    </div>
    </div>
    </div>
    </div>
    </div>

Areas/Admin/Views/AboutUs/Edit.cshtml
@model Yummy.Areas.Admin.ViewModels.AboutUsViewModel

@{
    ViewData["Title"] = "Edit";
}



<div class="full_container" style="margin-top:130px;margin-bottom:130px">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">
@* 
<div class="logo_login">
    <div class="center">
        <img width="210" src="~/images/logo/logo.png" alt="#" />
    </div>
</div>
 *@
<div class="login_form">

    <form asp-action="Edit" enctype="multipart/form-data" class="row g-3">
        <fieldset>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="field">
                <label asp-for="File1" class="control-label"></label>
                <input asp-for="File1" class="form-control" />
                <span asp-validation-for="File1" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="File2" class="control-label"></label>
                <input asp-for="File2" class="form-control" />
                <span asp-validation-for="File2" class="text-danger"></span>
            </div>
           <div class="field">
                <label asp-for="AboutUsParagraph1" class="control-label"></label>
                <input asp-for="AboutUsParagraph1" class="form-control" />
                <span asp-validation-for="AboutUsParagraph1" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsParagraph2" class="control-label"></label>
                <input asp-for="AboutUsParagraph2" class="form-control" />
                <span asp-validation-for="AboutUsParagraph2" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPoint1" class="control-label"></label>
                <input asp-for="AboutUsPoint1" class="form-control" />
                <span asp-validation-for="AboutUsPoint1" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPoint2" class="control-label"></label>
                <input asp-for="AboutUsPoint2" class="form-control" />
                <span asp-validation-for="AboutUsPoint2" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPoint3" class="control-label"></label>
                <input asp-for="AboutUsPoint3" class="form-control" />
                <span asp-validation-for="AboutUsPoint3" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsLink" class="control-label"></label>
                <input asp-for="AboutUsLink" class="form-control" />
                <span asp-validation-for="AboutUsLink" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsTitle" class="control-label"></label>
                <input asp-for="AboutUsTitle" class="form-control" />
                <span asp-validation-for="AboutUsTitle" class="text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="AboutUsPhoneNote" class="control-label"></label>
                <input asp-for="AboutUsPhoneNote" class="form-control" />
                <span asp-validation-for="AboutUsPhoneNote" class="text-danger"></span>
            </div>
           
            

            <div class="text-center mb-3 ">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
           
            <div class="text-center">
                <a asp-action="Index" class="btn btn-success">Back to Table</a>
            </div>
            </fieldset>
        </form>
    </div>
    </div>
    </div>
    </div>
    </div>

Areas/Admin/Views/AboutUs/Index.cshtml
@model IEnumerable<Yummy.Models.AboutUs>

@{
    ViewData["Title"] = "Index";
}


<div class="full_container">
    <div class="container">
        <div class="full_height">
          <div class="col-md-12 mb-3">
            <div class="white_shd full margin_bottom_30">
        <div class="full graph_head">
            <div class="heading1 margin_0">
        <h2>
            
                <a asp-action="Create">Create New</a>
            
        </h2>
            </div>
        </div>
 <div class="table_section padding_infor_info">
     <div class="table-responsive-sm">
       <table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AboutUsImage1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AboutUsImage2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AboutUsParagraph1)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.AboutUsParagraph2)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.AboutUsPoint1)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.AboutUsPoint2)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.AboutUsPoint3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AboutUsLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AboutUsTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AboutUsPhoneNote)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="~/AboutUsImg/@item.AboutUsImage1" style="width:90px;height:90px"/>
            </td>
            <td>
                <img src="~/AboutUsImg/@item.AboutUsImage2" style="width:90px;height:90px" />
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsParagraph1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsParagraph2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsPoint1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsPoint2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsPoint3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AboutUsPhoneNote)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.AboutUsId"><i class="fa fa-edit"> </i></a> |
                <a href="" class="butDelehhh" data-toggle="modal" data-target="#myModal" data-bfc=@Url.ActionLink("Delete","AboutUs",new{idDelete = item.AboutUsId})><i class="fa fa-close"></i></a> |
                    @if (item.IsActive)
                    {
                        <a asp-action="Active" asp-route-idActive="@item.AboutUsId"><i class="fa fa-eye"></i></a>
                    }
                    else{
                        <a asp-action="Active" asp-route-idActive="@item.AboutUsId"><i class="fa fa-eye-slash"></i></a>
                    }
                      
               
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
                Are you sure?
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button id="confirmDelt" type="button" class="btn btn-danger" data-dismiss="modal">Delete</button>
                <button id="cancelDelt" type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/jquery/jquery.js"></script>



<script>
    var dataDeleteInfo = "";
    $(".butDelehhh").click(function () {
        dataDeleteInfo = $(this).data("bfc")
    })

    $("#confirmDelt").click(function () {
        window.location = dataDeleteInfo;
        dataDeleteInfo = ""
    })

    $("#cancelDelt").click(function () {
        dataDeleteInfo = ""
    })

</script>