Areas/Admin/ViewModels/FrontOfPageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Yummy.Areas.Admin.ViewModels
{
    public class FrontOfPageViewModel:BaseModelVM
    {
        [Required]
        [Display(Name ="Title")]
        public string FrontOfPageTitle { get; set; }
        [Required]
        [Display(Name = "Description")]
        public string FrontOfPageDescription { get; set; }
        [Required]
        [Display(Name = "Link1")]
        public string FrontOfPageLink1 { get; set; }
        [Required]
        [Display(Name = "Link2")]
        public string FrontOfPageLink2 { get; set; }
        [Display(Name = "Image")]
        public string FrontOfPageImage { get; set; }
        [Display(Name = "File")]
        public IFormFile? File { get; set; }
    }
}

Models/FrontOfPage.cs
using System.ComponentModel.DataAnnotations;

namespace Yummy.Models
{
    public class FrontOfPage:BaseEntity
    {
        public int FrontOfPageId { get; set; }
        [Display(Name = "Title")]
        public string FrontOfPageTitle { get; set; }
        [Display(Name = "Description")]
        public string FrontOfPageDescription { get; set; }
        [Display(Name = "Link1")]
        public string FrontOfPageLink1 { get; set; }
        [Display(Name = "Link2")]
        public string FrontOfPageLink2 { get; set; }
        [Display(Name = "Image")]
        public string FrontOfPageImage { get; set; }


    }
}

Areas/Admin/Controllers/FrontOfPageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Yummy.Areas.Admin.ViewModels;
using Yummy.Models;
using Yummy.Models.Repositories;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Yummy.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class FrontOfPageController : Controller
    {
        public IRepository<FrontOfPage> _FrontOfPage { get; }
        public IHostingEnvironment Host { get; }

        public FrontOfPageController(IRepository<FrontOfPage> frontOfPage,IHostingEnvironment host)
        {
            _FrontOfPage = frontOfPage;
            Host = host;
        }
        // GET: FrontOfPageController
        public ActionResult Index()
        {
            return View(_FrontOfPage.View());
        }


        // GET: FrontOfPageController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FrontOfPageController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FrontOfPageViewModel collection)
        {
            try
            {
                if (collection.File == null)
                {

                    ModelState.AddModelError("", "The file field is required ");
                    return View();

                }
                var obj = new FrontOfPage
                {
                    FrontOfPageDescription = collection.FrontOfPageDescription,
                    FrontOfPageLink1 = collection.FrontOfPageLink1,
                    FrontOfPageLink2 = collection.FrontOfPageLink2,
                    FrontOfPageTitle = collection.FrontOfPageTitle,
                    FrontOfPageImage = UplaodImage(collection.File),
                    CreateDate = DateTime.Now,
                    CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    IsActive = true,
                };
                _FrontOfPage.Add(obj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FrontOfPageController/Edit/5
        public ActionResult Edit(int id)
        {

            var data = _FrontOfPage.Find(id);
            var obj = new FrontOfPageViewModel
            {
                FrontOfPageDescription = data.FrontOfPageDescription,
                FrontOfPageLink1 = data.FrontOfPageLink1,   
                FrontOfPageTitle = data.FrontOfPageTitle,
                FrontOfPageLink2 = data.FrontOfPageLink2,
            };
            return View(obj);
        }

        // POST: FrontOfPageController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FrontOfPageViewModel collection)
        {
            try
            {

              
                var data = _FrontOfPage.Find(id);
                data.FrontOfPageLink1 = collection.FrontOfPageLink1;
                data.FrontOfPageLink2 = collection.FrontOfPageLink2;
                data.FrontOfPageTitle = collection.FrontOfPageTitle;
                data.FrontOfPageDescription = collection.FrontOfPageDescription;
                data.FrontOfPageImage = (collection.File !=null)?UplaodImage(collection.File):data.FrontOfPageImage;
                data.EditDate = DateTime.Now;
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _FrontOfPage.Update(id,data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FrontOfPageController/Delete/5
        public ActionResult Delete(int idDelete)
        {
            var data = _FrontOfPage.Find(idDelete);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _FrontOfPage.Delete(idDelete,data);
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Active(int idActive)
        {
            var data = _FrontOfPage.Find(idActive);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _FrontOfPage.Active(idActive, data);
            return RedirectToAction(nameof(Index));
        }


        public string UplaodImage(IFormFile file)
        {
            string image = "";
            if (file != null)
            {
                string path = Path.Combine(Host.WebRootPath,"FrontOfPageImg");
                FileInfo info  = new FileInfo(file.FileName);
                image = Guid.NewGuid() +info.Extension;
                string FullPath = Path.Combine(path,image);
                file.CopyTo(new FileStream( FullPath, FileMode.Create));
            }
            return image;
        }
    }
}

Areas/Admin/Views/FrontOfPage/Create.cshtml
@model Yummy.Areas.Admin.ViewModels.FrontOfPageViewModel

@{
    ViewData["Title"] = "Create";
}


<div class="full_container">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

                <div class="logo_login">
                    <div class="center">
                        <img width="210" src="~/images/logo/logo.png" alt="#" />
                    </div>
                </div>

                <div class="login_form">

                    <form asp-action="Create" enctype="multipart/form-data" class="row g-3">
                        <fieldset>
                            <div class="field">
                                <label asp-for="FrontOfPageDescription" class="control-label"></label>
                                <input asp-for="FrontOfPageDescription" class="form-control" />
                                <span asp-validation-for="FrontOfPageDescription" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="FrontOfPageLink1" class="control-label"></label>
                                <input asp-for="FrontOfPageLink1" class="form-control" />
                                <span asp-validation-for="FrontOfPageLink1" class="text-danger"></span>
                            </div>

                            <div class="field">
                                <label asp-for="FrontOfPageLink2" class="control-label"></label>
                                <input asp-for="FrontOfPageLink2" class="form-control" />
                                <span asp-validation-for="FrontOfPageLink2" class="text-danger"></span>
                            </div>

                            <div class="field">
                                <label asp-for="FrontOfPageTitle" class="control-label"></label>
                                <input asp-for="FrontOfPageTitle" class="form-control" />
                                <span asp-validation-for="FrontOfPageTitle" class="text-danger"></span>
                            </div>

                            <div class="field mb-5">
                                <label asp-for="File" class="control-label"></label>
                                <input asp-for="File" class="form-control" />
                                <span asp-validation-for="File" class="text-danger"></span>
                            </div>
                            <div asp-validation-summary="ModelOnly" class="text-danger "></div>


                            <div class="text-center mb-2 mt-2  ">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                            <div class="text-center">
                                <a asp-action="Index" class="btn btn-success">Back to Table</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/FrontOfPage/Edit.cshtml
@model Yummy.Areas.Admin.ViewModels.FrontOfPageViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="full_container">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

                <div class="logo_login">
                    <div class="center">
                        <img width="210" src="~/images/logo/logo.png" alt="#" />
                    </div>
                </div>

                <div class="login_form">

                    <form asp-action="Edit" enctype="multipart/form-data" class="row g-3">
                        <fieldset>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="field">
                                <label asp-for="FrontOfPageDescription" class="control-label"></label>
                                <input asp-for="FrontOfPageDescription" class="form-control" />
                                <span asp-validation-for="FrontOfPageDescription" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="FrontOfPageLink1" class="control-label"></label>
                                <input asp-for="FrontOfPageLink1" class="form-control" />
                                <span asp-validation-for="FrontOfPageLink1" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="FrontOfPageLink2" class="control-label"></label>
                                <input asp-for="FrontOfPageLink2" class="form-control" />
                                <span asp-validation-for="FrontOfPageLink2" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="FrontOfPageTitle" class="control-label"></label>
                                <input asp-for="FrontOfPageTitle" class="form-control" />
                                <span asp-validation-for="FrontOfPageTitle" class="text-danger"></span>
                            </div>
                            <div class="field">
                                <label asp-for="File" class="control-label"></label>
                                <input asp-for="File" class="form-control" />
                                <span asp-validation-for="File" class="text-danger"></span>
                            </div>

                            <div class="text-center mb-2 ">
                                <input type="submit" value="Edit" class="btn btn-primary" />
                            </div>
                            <div class="text-center">
                                <a asp-action="Index" class="btn btn-success">Back to Table</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/FrontOfPage/Index.cshtml
@model IEnumerable<Yummy.Models.FrontOfPage>

@{
    ViewData["Title"] = "Index";
}


<div class="full_container">
    <div class="container">
        <div class="full_height">
          <div class="col-md-12 mb-3">
            <div class="white_shd full margin_bottom_30">
        <div class="full graph_head">
            <div class="heading1 margin_0">
        <h2>
            
                <a asp-action="Create">Create New</a>
            
        </h2>
            </div>
        </div>
 <div class="table_section padding_infor_info">
     <div class="table-responsive-sm">
       <table class="table table-dark table-striped">    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FrontOfPageTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrontOfPageDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrontOfPageLink1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrontOfPageLink2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FrontOfPageImage)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FrontOfPageTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FrontOfPageDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FrontOfPageLink1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FrontOfPageLink2)
            </td>
            <td>
                <img src="~/FrontOfPageImg/@item.FrontOfPageImage" style="width:90px;height:90px"/>
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.FrontOfPageId"><i class="fa fa-edit"> </i></a> |
                <a href="" class="butDelehhh" data-toggle="modal" data-target="#myModal" data-bfc=@Url.ActionLink("Delete","FrontOfPage",new{idDelete = item.FrontOfPageId})><i class="fa fa-close"></i></a> |
                    @if (item.IsActive)
                    {
                        <a asp-action="Active" asp-route-idActive="@item.FrontOfPageId"><i class="fa fa-eye"></i></a>
                    }
                    else{
                        <a asp-action="Active" asp-route-idActive="@item.FrontOfPageId"><i class="fa fa-eye-slash"></i></a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>



<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
                Are you sure?
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button id="confirmDelt" type="button" class="btn btn-danger" data-dismiss="modal">Delete</button>
                <button id="cancelDelt" type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/jquery/jquery.js"></script>



<script>
    var dataDeleteInfo = "";
    $(".butDelehhh").click(function () {
        dataDeleteInfo = $(this).data("bfc")
    })

    $("#confirmDelt").click(function () {
        window.location = dataDeleteInfo;
        dataDeleteInfo = ""
    })

    $("#cancelDelt").click(function () {
        dataDeleteInfo = ""
    })

</script>