Models/MainMenu.cs
using System.ComponentModel.DataAnnotations;

namespace Yummy.Models
{
    public class MainMenu:BaseEntity
    {
        public int MainMenuId { get; set; }
        [Display(Name = "Icon URL")]
        public string MainMenuIconUrl { get; set; }

    }
}

Areas/Admin/Controllers/MainMenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;
using System.Security.Claims;
using Yummy.Models;
using Yummy.Models.Repositories;

namespace Yummy.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MainMenuController : Controller
    {
        public IRepository<MainMenu> _MainMenu { get; }

        public MainMenuController(IRepository<MainMenu> mainMenu)
        {
            _MainMenu = mainMenu;
        }
        // GET: MainMenuController
        public ActionResult Index()
        {
            return View(_MainMenu.View());
        }

       

        // GET: MainMenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MainMenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MainMenu collection)
        {
            try
            {
                collection.CreateDate = DateTime.Now;
                collection.CreateUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                collection.IsActive = true;
                _MainMenu.Add(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MainMenuController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_MainMenu.Find(id));
        }

        // POST: MainMenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MainMenu collection)
        {
            try
            {
                var data = _MainMenu.Find(id);
                data.MainMenuIconUrl = collection.MainMenuIconUrl;
                data.EditDate = DateTime.Now;
                data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _MainMenu.Update(id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MainMenuController/Delete/5
        public ActionResult Delete(int idDelete)
        {
            var data = _MainMenu.Find(idDelete);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _MainMenu.Delete(idDelete, data);
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Active(int idActive)
        {
            var data = _MainMenu.Find(idActive);
            data.EditDate = DateTime.Now;
            data.EditUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _MainMenu.Active(idActive, data);
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/MainMenu/Create.cshtml
@model Yummy.Models.MainMenu

@{
    ViewData["Title"] = "Create";
}

<div class="full_container">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

                <div class="logo_login">
                    <div class="center">
                        <img width="210" src="~/images/logo/logo.png" alt="#" />
                    </div>
                </div>

                <div class="login_form">

                    <form asp-action="Create"  class="row g-3">
                        <fieldset>
                            <div asp-validation-summary="ModelOnly" class="text-danger "></div>

                            <div class="field">
                                <label asp-for="MainMenuIconUrl" class="control-label"></label>
                                <input asp-for="MainMenuIconUrl" class="form-control" />
                                <span asp-validation-for="MainMenuIconUrl" class="text-danger"></span>
                            </div>
                           

                           

                            <div class="text-center mb-2 mt-2">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                            <div class="text-center">
                                <a asp-action="Index" class="btn btn-success">Back to Table</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/MainMenu/Edit.cshtml
@model Yummy.Models.MainMenu

@{
    ViewData["Title"] = "Edit";
}


<div class="full_container">
    <div class="container">
        <div class="center verticle_center full_height">
            <div class="login_section">

                <div class="logo_login">
                    <div class="center">
                        <img width="210" src="~/images/logo/logo.png" alt="#" />
                    </div>
                </div>

                <div class="login_form">

                    <form asp-action="Edit"  class="row g-3">
                        <fieldset>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="field">
                                <label asp-for="MainMenuIconUrl" class="control-label"></label>
                                <input asp-for="MainMenuIconUrl" class="form-control" />
                                <span asp-validation-for="MainMenuIconUrl" class="text-danger"></span>
                            </div>



                            <div class="text-center mb-2 ">
                                <input type="submit" value="Edit" class="btn btn-primary" />
                            </div>
                            <div class="text-center">
                                <a asp-action="Index" class="btn btn-success">Back to Table</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/MainMenu/Index.cshtml
@model IEnumerable<Yummy.Models.MainMenu>

@{
    ViewData["Title"] = "Index";
}


<div class="full_container">
    <div class="container">
        <div class="full_height">
            <div class="col-md-12 mb-3">
                <div class="white_shd full margin_bottom_30">
                    <div class="full graph_head">
                        <div class="heading1 margin_0">
                            <h2>

                                <a asp-action="Create">Create New</a>

                            </h2>
                        </div>
                    </div>
                    <div class="table_section padding_infor_info">
                        <div class="table-responsive-sm">
                            <table class="table table-dark table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.MainMenuIconUrl)
                                        </th>
                                        
                                        

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MainMenuIconUrl)
                                            </td>
                                            
                                            

                                            <td>
                                                <a asp-action="Edit" asp-route-id="@item.MainMenuId"><i class="fa fa-edit"> </i></a> |
                                                <a href="" class="butDelehhh" data-toggle="modal" data-target="#myModal" data-bfc=@Url.ActionLink("Delete","MainMenu",new{idDelete = item.MainMenuId})><i class="fa fa-close"></i></a> |
                                                @if (item.IsActive)
                                                {
                                                    <a asp-action="Active" asp-route-idActive="@item.MainMenuId"><i class="fa fa-eye"></i></a>
                                                }
                                                else
                                                {
                                                    <a asp-action="Active" asp-route-idActive="@item.MainMenuId"><i class="fa fa-eye-slash"></i></a>
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal body -->
            <div class="modal-body">
                Are you sure?
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button id="confirmDelt" type="button" class="btn btn-danger" data-dismiss="modal">Delete</button>
                <button id="cancelDelt" type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/jquery/jquery.js"></script>



<script>
    var dataDeleteInfo = "";
    $(".butDelehhh").click(function () {
        dataDeleteInfo = $(this).data("bfc")
    })

    $("#confirmDelt").click(function () {
        window.location = dataDeleteInfo;
        dataDeleteInfo = ""
    })

    $("#cancelDelt").click(function () {
        dataDeleteInfo = ""
    })

</script>